export {default as Logo} from "./Logo"
// export {default as LogoDesktop} from "./logoDesktop"
export {default as Next} from "./Next"
export {default as Back} from "./Back"
export {default as View} from "./View"